### ISSUE TITLE
QuizCard

### ISSUE THREAD

**Issue by incredibleLeitman** [brandonshawfhl/Quiz-Maker#10]
I see you have adapted your previous data structure:
https://github.com/brandonshawfhl/Quiz-Maker/blob/74beca70da6633606212c638483b3aa5c735ba0b/ConsoleApp3/QuizCard.cs#L3-L10

Not sure how it was before, but now it is in a much cleaner state: Classes usually represent the blueprint for one specific item -> in this case this is one QuizCard ("QuestionAndAnswers" or just "QnA" would also be possible names here)
If you need multiple elements (what you probably will do when creating a whole quiz with multiple questions and answers) you just create a list that holds elements of your data class :D

However 👆 what you initially thought of by having all questions and answers in one item is also a common pattern and called "data oriented design" that you can look up if you want to. This is often used in game development or when performance is critical,
but its much harder to maintain the code and understand, especially for beginners.

Regarding this issue, I think you should just rethink the list "allAnswers" -> is this the combination of all incorrect plus the correct answer? Because this would be kinda redundant, why storing the correct answer twice?
(and maybe naming: "printQuestions" is plural, and why the "print" part? :D)

**Comment by incredibleLeitman** [comment]
Sorry maybe I have confused you 🙈 

The only part to do in this issues was meant to be
> Regarding this issue, I think you should just rethink the list "allAnswers" -> is this the combination of all incorrect plus the correct answer? Because this would be kinda redundant, why storing the correct answer twice?
(and maybe naming: "printQuestions" is plural, and why the "print" part? :D)

**Comment by brandonshawfhl** [comment]
No you didn't confuse me, but I was just trying to do the other common pattern you were referring to. I assumed that other approach involved making the answers and questions separate objects. I just didn't think this project was complex enough for that.

It is redundant, but its a lot harder at my level to do it the other way. either way I'm going to have to create another list to store them before I print them. I was just already doing it in the object rather than in my future loop.

**Comment by incredibleLeitman** [comment]
Nice work on that :D 👍 

Sorry for the resulted extra work, I was just mentioning dod to give you some insight into other approaches. You weren't meant to implement those 🙈 
We in this course have settled to teach our clients how to write good code that is easy to undertand and maintain, because this is what you probably need most in your future carreer. The approach of scrambling data into just nameless structures to increase performance is only a very niche edge case used for example in game development or when working on embedded platforms that have low memory and cpu. 

One major lesson on coding: Do things that increase performance *last and only if they are really needed*!
99,9 % percent of the time you dont need those extra nano seconds and few kByte of more memory but your code gets so much worse in all belongings xD
