### ISSUE TITLE
Main logic of loading and creation of quiz unclear

### ISSUE THREAD

**Issue by mayisa87** [brandonshawfhl/Quiz-Maker#25]
https://github.com/brandonshawfhl/Quiz-Maker/blob/31885e18b19366e38056536bfd044eaaadf721a3/ConsoleApp3/Program.cs#L33-L39

To me the main logic is not yet clear. First you ask user what he wants to do, if he chooses "Make a quiz" you create the new quiz, fill the data and store it to your "**madeQuiz**" variable

Then, outside of your if, you shuffle the data of the List holding the QuizCards, and store it to the **currentQuiz** list. but... then you have the other ifs too, like "Load" and "Save" 

**_So what is unclear to me:_**
If user does not choose to make a new quiz, you will anyway execute Shuffling of the madeList ... which is empty...  So from my point of view those two lines should be moved after the ifs of loading and saving.
https://github.com/brandonshawfhl/Quiz-Maker/blob/31885e18b19366e38056536bfd044eaaadf721a3/ConsoleApp3/Program.cs#L33-L34
And instead of storing the loaded quiz data to **"currentQuiz"** you should maybe store it to "**madeQuiz"**

**_Why?_** 
If you move those lines of shuffling QuizCards in List and answers after your ifs, you can be sure that also in case of loaded data, your Quiz will be randomized.

**Comment by brandonshawfhl** [comment]
Well my main issue with that is I can't loading and saving to work in the first place so I didn't really know how that was going to work and was going to deal with it after I could get loading and saving to work
Please see issue #20
