### ISSUE TITLE
Try to introduce enums to your application

### ISSUE THREAD

**Issue by mayisa87** [brandonshawfhl/Quiz-Maker#3]
https://github.com/brandonshawfhl/Quiz-Maker/blob/218bd803462849693a3d4dd87d132ad66a5b04c7/ConsoleApp3/UserInterface.cs#L70

If you haven't tried it before, this would be a good point for you, to introduce enums to the project. Especially for things like user choices you can have a seperated file, like "UserInputChoice" and define in there a public enum with same name.

Have a look to the videos about enums in teachable.

**Comment by brandonshawfhl** [comment]
I did have enums in the program originally, but I had a hard time executing them correctly so I just switched to something I knew so I could continue  on with the code since you guys were on a break.

**Comment by brandonshawfhl** [comment]
Also the teachable video that I have seen on enums at this point does not dictate how to manage an enum as a separate file. It only shows how to do it for the file you are in.
