### ISSUE TITLE
Not sure what is the goal of this method?

### ISSUE THREAD

**Issue by mayisa87** [brandonshawfhl/Quiz-Maker#6]
https://github.com/brandonshawfhl/Quiz-Maker/blob/218bd803462849693a3d4dd87d132ad66a5b04c7/ConsoleApp3/Logic.cs#L31

So I'm not yet sure what this method intends to do? Shuffling? Take care about your list object you give as parameter, there is a difference between using simple primitive datatypes (like int, double, bool ) or using objects so called reference data types. 

If you give an object as parameter, and you change the elements of your list in this example, and even delete it, they won't be there anymore afterwards in the Main() (calling method) too! So always take care about changing values of parameters objects.

See this video: https://course.raketementoring.com/courses/rakete-mentoring/lectures/45560440

And still I don't get exactly what you try to achieve here? First you create an hardcoded string[,] with the choices A-F,  then you create random number to access the list element on a random position and replace the value on this position with the A-F values of string array (but you take here [1,randomNumber] but before filled only row 0?) 

Very confusing to me. Please more infos :)

And rename your method + add an XML documentation so other developers know what your intention is.

https://course.raketementoring.com/courses/rakete-mentoring/lectures/45560452

**Comment by brandonshawfhl** [comment]
Yes I was coming up with a way to list the answers for each  question in random order, and I couldn't really figure out how to do that. If I filled a row it was by mistake and I just forgot which position is rows and which position is columns
